theme: jekyll-theme-minimal
logo: Jade001_Images/Jade001_NPMT_front.jpg
description: Large green jade dish (碧玉大盤) collected by the Qianlong Emperor.
玉盤博徑得二尺，圍六尺有（去聲）五寸益。
虛中盛水受一石，素質不雕其色碧。 
旁達孚尹瓊華澤，葆光撫不留手跡。
群玉之精出昆侖，吉日甲子天子賓。 
於西王母瑤池津，行觴介紹簠蓋樽。
爾時所御器今存，作鎮西極永好完。 
未入震旦三千年，問今何來不脛偶。
準噶爾亡淪世守，阿睦撒納茲竊取。 
王師深入靖孽醜，於將獲之聯猭走。
棄其重器為我有，元英大呂陳座右。 
咄哉玉盤徒華滋，不可食兮不可衣。
連城價詎如窮奇，俘彼禍除可罷師。 
前歌後舞樂雍熙，瑰玩吾將安用之。
擬付剿人一例椎。
