theme: jekyll-theme-minimal
title: Jade001 Large Green Jade Dish 碧玉大盤.
description: collected by the Qianlong Emperor.
description: 玉椀來回部,輸誠供闔閶,召公懷不寶,韓子戒無當,異致白毛鹿,引恬頳尾魴,勞徠非力并,天眷奉昭彰。
logo: Jade001_Images/Jade001_NPMT_front.jpg


